project:
  type: "website"

website:
  title: "CNG Education Working Group meeting notes"
  site-url: "https://geojupyter.org"

  repo-url: "https://cng-education.github.io/meeting-notes/"
  repo-actions: ["edit", "issue"]

  navbar:
    left: []


format:
  html:
    from: "markdown+emoji"
    theme:
      - "cosmo"
      - "brand"
    css: "styles.css"
    toc: true
